[package]
name = "rsbamtk"
version = "0.1.0"
edition = "2021"

[dependencies]
rust-htslib = { version = "*"}
bio = "*"
tempdir = "0.3.7"
clap = {version = "4.0.23", features = ["derive",]}
anyhow = "1.0"
log = "*"
rust-lapper = "1.1.0"
crossbeam = "*"
bstr = "1.4.0"
itertools = "*"