[package]
name = "rsbamtk"
version = "0.1.0"
edition = "2021"

[lib]
name = "rsbamtk"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-htslib = { version = "*"}
bio = "*"
tempdir = "0.3.7"